-   id: remove-trailing-comma
    name: Remove trailing commas
    description: Automatically remove trailing commas from calls and literals.
    entry: remove-trailing-comma
    language: python
    types: [python]
